### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zsszabo** [gshackles/Estimote-iOS-Xamarin#2]
Hi!

I would like to use your binding, but when i want to deploy my demo program to my iPad i received the following errors:

error MT5211: Native linking failed, undefined Objective-C class: _OBJC_CLASS_$_ESTBeaconDelegate. If '_OBJC_CLASS_$_ESTBeaconDelegate' is a protocol from a third-party binding, please check that it has the [Protocol] attribute in its api definition file, otherwise verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5211: Native linking failed, undefined Objective-C class: _OBJC_CLASS_$_ESTBeaconManagerDelegate. If '_OBJC_CLASS_$_ESTBeaconManagerDelegate' is a protocol from a third-party binding, please check that it has the [Protocol] attribute in its api definition file, otherwise verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_ESTBeaconDelegate. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_ESTBeaconManagerDelegate. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.

Can you help me?

Best Regards
  John Tailor

**Comment by gshackles** [comment]
Unfortunately my binding is pretty out of date at this point, so I'd actually recommend against using it for the time being. Updating the binding is definitely on my todo list but unfortunately it hasn't been something I've been able to carve out time for yet. Are you looking to use something specific to the Estimote SDK, or just interact with Estimote beacons in general? If it's the latter, I'd recommend just using the built-in APIs in iOS in CoreLocation in the meantime which work great with Estimote beacons.

**Comment by zsszabo** [comment]
Thanks your answer. I am working on a demo, so it is enough to I use the CoreLocation.

**Comment by mysterymaster** [comment]
Hi Greg , Could you update the binding and also give instructions on how to do it ? 

Its confusing for a beginner like me . Thanks

**Comment by jimbobbennett** [comment]
@mysterymaster - I've got some up to date bindings on my GitHub page:

https://github.com/jimbobbennett/EstimoteBinding

This is pretty much up to date, and I'm actively developing a sample app and trying to keep on top of the updates from Estimote.  I'll try to write a blog post tonight on how to go about doing it yourself as well - will update if I get round to it.

**Comment by jimbobbennett** [comment]
I've got some up to date bindings on my GitHub page:

https://github.com/jimbobbennett/EstimoteBinding

This is pretty much up to date, and I'm actively developing a sample app and trying to keep on top of the updates from Estimote.  I'll try to write a blog post tonight on how to go about doing it yourself as well - will update if I get round to it.

**Comment by jimbobbennett** [comment]
@mysterymaster  - Blogged - http://www.jimbobbennett.io/binding-ios-libraries-in-xamarin/

**Comment by gshackles** [comment]
I've now replaced my binding with [Xamarin's official binding](http://components.xamarin.com/view/estimotesdkios)
